# render.yaml
services:
  - type: web
    name: poromet-backend
    env: python
    region: tokyo
    repo: https://github.com/takeruhukushima/porometGUI
    branch: main
    rootDirectory: /backend  # バックエンドディレクトリをルートとして指定
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn server:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
    plan: free
    autoDeploy: true
    numInstances: 1
    ignoreFile: .gitignore
    healthCheckPath: /docs